sonar.projectKey=Luyox10_inventario-devops
sonar.projectName=Inventario DevOps - Backend
sonar.projectVersion=1.0
sonar.organization=luyox10

sonar.sources=src
sonar.language=js
sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=node_modules/**,coverage/**
