name: OWASP ZAP Scan

on:
  workflow_dispatch:

jobs:

  zap_scan:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Ejecutar OWASP ZAP
      uses: zaproxy/action-baseline@v0.12.0

      with:
        target: 'https://inventario-devops.onrender.com'
